function getDefaultProducts() {
  return [
    {
      id: 1,
      category: 'innerwear',
      name_ar: 'طقم ملابس داخلية قطن 3 قطعة',
      name_en: 'Cotton Innerwear Set 3 Pieces',
      description_ar: 'طقم ملابس داخلية قطنية ناعمة وآمنة على بشرة الأطفال، مكون من 3 قطع بألوان مبهجة',
      description_en: 'Soft cotton innerwear set safe for children\'s skin, 3 pieces with cheerful colors',
      price: 185,
      images: ['https://placehold.co/400x500/F3B423/1D355E?text=طقم+داخلي'],
      variants: [
        { size: '2', stock: 10 },
        { size: '3', stock: 8 },
        { size: '4', stock: 12 },
        { size: '5', stock: 6 },
        { size: '6', stock: 4 },
      ],
      createdAt: '2026-01-15',
    },
    {
      id: 2,
      category: 'pajamas',
      name_ar: 'بيجامة شتوية قطيفة',
      name_en: 'Winter Fleece Pajama',
      description_ar: 'بيجامة شتوية من القطيفة الناعمة، توفر الدفء والراحة لطفلك خلال الليل',
      description_en: 'Winter fleece pajama, soft and warm for your child\'s comfort at night',
      price: 320,
      images: ['https://placehold.co/400x500/1D355E/F3B423?text=بيجامة'],
      variants: [
        { size: '2', stock: 7 },
        { size: '3', stock: 5 },
        { size: '4', stock: 0 },
        { size: '5', stock: 9 },
        { size: '6', stock: 3 },
        { size: '7', stock: 6 },
      ],
      createdAt: '2026-01-20',
    },
    {
      id: 3,
      category: 'tshirts',
      name_ar: 'تيشيرت قطني بأكمام قصيرة',
      name_en: 'Cotton Short Sleeve T-Shirt',
      description_ar: 'تيشيرت قطني 100% بأكمام قصيرة، ألوان زاهية تناسب جميع الأوقات',
      description_en: '100% cotton short sleeve t-shirt, vibrant colors suitable for all occasions',
      price: 150,
      images: ['https://placehold.co/400x500/F3B423/1D355E?text=تيشيرت'],
      variants: [
        { size: '2', stock: 15 },
        { size: '3', stock: 12 },
        { size: '4', stock: 10 },
        { size: '5', stock: 8 },
        { size: '6', stock: 6 },
        { size: '7', stock: 4 },
        { size: '8', stock: 2 },
      ],
      createdAt: '2026-02-01',
    },
    {
      id: 4,
      category: 'pants',
      name_ar: 'بنطلون جينز أطفال',
      name_en: 'Kids Jeans Pants',
      description_ar: 'بنطلون جينز مريح للأطفال، قماش مرن يناسب الحركة اليومية',
      description_en: 'Comfortable kids jeans, flexible fabric suitable for daily wear',
      price: 280,
      images: ['https://placehold.co/400x500/1D355E/F3B423?text=جينز'],
      variants: [
        { size: '3', stock: 8 },
        { size: '4', stock: 10 },
        { size: '5', stock: 7 },
        { size: '6', stock: 5 },
        { size: '7', stock: 0 },
        { size: '8', stock: 4 },
      ],
      createdAt: '2026-02-05',
    },
    {
      id: 5,
      category: 'jackets',
      name_ar: 'جاكت مبطن شتوي',
      name_en: 'Winter Padded Jacket',
      description_ar: 'جاكت شتوي مبطن عازل للبرودة، تصميم أنيق بألوان عصرية',
      description_en: 'Winter padded jacket, cold-resistant with stylish modern design',
      price: 450,
      images: ['https://placehold.co/400x500/F3B423/1D355E?text=جاكت'],
      variants: [
        { size: '2', stock: 5 },
        { size: '3', stock: 7 },
        { size: '4', stock: 6 },
        { size: '5', stock: 4 },
        { size: '6', stock: 3 },
      ],
      createdAt: '2026-02-10',
    },
    {
      id: 6,
      category: 'dresses',
      name_ar: 'فستان بناتي دانتيل',
      name_en: 'Girls Lace Dress',
      description_ar: 'فستان بناتي أنيق بتفاصيل دانتيل ناعمة، مثالي للمناسبات والخروجات',
      description_en: 'Elegant girls dress with soft lace details, perfect for occasions',
      price: 380,
      images: ['https://placehold.co/400x500/1D355E/F3B423?text=فستان'],
      variants: [
        { size: '2', stock: 6 },
        { size: '3', stock: 8 },
        { size: '4', stock: 0 },
        { size: '5', stock: 5 },
        { size: '6', stock: 7 },
        { size: '7', stock: 3 },
      ],
      createdAt: '2026-02-15',
    },
    {
      id: 7,
      category: 'sets',
      name_ar: 'طقم صيفي (تيشيرت + شورت)',
      name_en: 'Summer Set (T-Shirt + Shorts)',
      description_ar: 'طقم صيفي أنيق مكون من تيشيرت وشورت قطن، مريح للأجواء الحارة',
      description_en: 'Elegant summer set with cotton t-shirt and shorts, comfortable for hot weather',
      price: 290,
      images: ['https://placehold.co/400x500/F3B423/1D355E?text=طقم+صيفي'],
      variants: [
        { size: '2', stock: 10 },
        { size: '3', stock: 8 },
        { size: '4', stock: 6 },
        { size: '5', stock: 0 },
        { size: '6', stock: 4 },
      ],
      createdAt: '2026-03-01',
    },
    {
      id: 8,
      category: 'accessories',
      name_ar: 'طاقية صيفية واقية من الشمس',
      name_en: 'Summer Sun Protection Hat',
      description_ar: 'طاقية صيفية عصرية تحمي طفلك من أشعة الشمس، تصميم لطيف ومبهج',
      description_en: 'Stylish summer hat protecting your child from sun, cute and cheerful design',
      price: 85,
      images: ['https://placehold.co/400x500/1D355E/F3B423?text=طاقية'],
      variants: [
        { size: '2', stock: 20 },
        { size: '3', stock: 15 },
        { size: '4', stock: 12 },
        { size: '5', stock: 8 },
      ],
      createdAt: '2026-03-05',
    },
    {
      id: 9,
      category: 'pajamas',
      name_ar: 'بيجامة صيفية قطنية',
      name_en: 'Summer Cotton Pajama',
      description_ar: 'بيجامة صيفية خفيفة من القطن العضوي، مناسبة للأجواء الحارة',
      description_en: 'Light summer pajama made of organic cotton, suitable for hot weather',
      price: 260,
      images: ['https://placehold.co/400x500/F3B423/1D355E?text=بيجامة+صيفية'],
      variants: [
        { size: '2', stock: 8 },
        { size: '3', stock: 10 },
        { size: '4', stock: 7 },
        { size: '5', stock: 5 },
        { size: '6', stock: 0 },
      ],
      createdAt: '2026-03-10',
    },
    {
      id: 10,
      category: 'innerwear',
      name_ar: 'فانلة داخلية قطن بأكمام طويلة',
      name_en: 'Cotton Long Sleeve Undershirt',
      description_ar: 'فانلة داخلية قطن بأكمام طويلة، ناعمة ومناسبة للشتاء',
      description_en: 'Cotton long sleeve undershirt, soft and suitable for winter',
      price: 110,
      images: ['https://placehold.co/400x500/1D355E/F3B423?text=فانلة'],
      variants: [
        { size: '2', stock: 14 },
        { size: '3', stock: 12 },
        { size: '4', stock: 10 },
        { size: '5', stock: 8 },
        { size: '6', stock: 6 },
        { size: '7', stock: 4 },
        { size: '8', stock: 3 },
      ],
      createdAt: '2026-03-15',
    },
    {
      id: 11,
      category: 'tshirts',
      name_ar: 'تيشيرت قطني مطبوع عليه رسوم كرتون',
      name_en: 'Cotton T-Shirt with Cartoon Print',
      description_ar: 'تيشيرت قطني بأكمام قصيرة مطبوع عليه رسوم كرتونية محببة للأطفال',
      description_en: 'Cotton short sleeve t-shirt with cartoon prints kids love',
      price: 170,
      images: ['https://placehold.co/400x500/F3B423/1D355E?text=مطبوع'],
      variants: [
        { size: '2', stock: 18 },
        { size: '3', stock: 14 },
        { size: '4', stock: 11 },
        { size: '5', stock: 0 },
        { size: '6', stock: 0 },
      ],
      createdAt: '2026-03-20',
    },
    {
      id: 12,
      category: 'dresses',
      name_ar: 'فستان تول للأميرات',
      name_en: 'Princess Tulle Dress',
      description_ar: 'فستان تول أميري مع تفاصيل لامعة، مثالي للحفلات والمناسبات الخاصة',
      description_en: 'Princess tulle dress with sparkling details, perfect for parties',
      price: 520,
      images: ['https://placehold.co/400x500/1D355E/F3B423?text=تول'],
      variants: [
        { size: '3', stock: 4 },
        { size: '4', stock: 0 },
        { size: '5', stock: 6 },
        { size: '6', stock: 3 },
        { size: '7', stock: 2 },
      ],
      createdAt: '2026-03-25',
    },
  ];
}

function getDefaultCoupons() {
  return [
    {
      id: 1,
      code: 'أوتوماتيك',
      type: 'percentage',
      value: 5,
      autoApply: true,
      conditions: { minItems: 4, minAmount: null, category: null, size: null },
      active: true,
      label_ar: 'خصم 5% عند شراء 4 قطع أو أكثر',
      label_en: '5% off when buying 4+ items',
    },
    {
      id: 2,
      code: 'أوتوماتيك',
      type: 'fixed',
      value: 100,
      autoApply: true,
      conditions: { minItems: null, minAmount: 1000, category: null, size: null },
      active: true,
      label_ar: 'خصم 100 جنيه للطلبات فوق 1000 جنيه',
      label_en: '100 EGP off for orders over 1000 EGP',
    },
    {
      id: 3,
      code: 'أوتوماتيك',
      type: 'percentage',
      value: 10,
      autoApply: true,
      conditions: { minItems: null, minAmount: null, category: null, size: '4' },
      active: true,
      label_ar: 'خصم 10% على مقاس 4',
      label_en: '10% off on size 4',
    },
    {
      id: 4,
      code: 'CUTE10',
      type: 'percentage',
      value: 10,
      autoApply: false,
      conditions: { minItems: null, minAmount: null, category: null, size: null },
      active: true,
      label_ar: 'كود CUTE10 → خصم 10% على كل المنتجات',
      label_en: 'Code CUTE10 → 10% off all products',
      maxUses: 50,
    },
    {
      id: 5,
      code: 'WELCOME',
      type: 'fixed',
      value: 50,
      autoApply: false,
      conditions: { minItems: null, minAmount: 300, category: null, size: null },
      active: true,
      label_ar: 'كود WELCOME → خصم 50 جنيه للطلبات فوق 300 جنيه',
      label_en: 'Code WELCOME → 50 EGP off for orders over 300 EGP',
      maxUses: 100,
    },
    {
      id: 6,
      code: 'INNER20',
      type: 'percentage',
      value: 20,
      autoApply: false,
      conditions: { minItems: null, minAmount: null, category: 'innerwear', size: null },
      active: true,
      label_ar: 'كود INNER20 → خصم 20% على الملابس الداخلية',
      label_en: 'Code INNER20 → 20% off on innerwear',
      maxUses: 30,
    },
  ];
}
