const { Client } = require('pg');

async function setupDatabase() {
  const client = new Client({
    connectionString: 'postgresql://postgres.nbqkgekosqyupfvpruao:Ahmed%40123Bup@aws-1-eu-central-1.pooler.supabase.com:6543/postgres',
    ssl: { rejectUnauthorized: false },
  });

  try {
    console.log('Connecting to Supabase...');
    await client.connect();
    console.log('Connected! Setting up database...');

    // Create trigger function first
    await client.query(`
      CREATE OR REPLACE FUNCTION public.handle_new_user()
      RETURNS TRIGGER AS $$
      BEGIN
        INSERT INTO public.profiles (id, full_name, phone, role)
        VALUES (
          NEW.id,
          COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
          COALESCE(NEW.raw_user_meta_data->>'phone', ''),
          CASE
            WHEN (SELECT COUNT(*) FROM public.profiles) = 0 THEN 'admin'
            ELSE 'user'
          END
        );
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql SECURITY DEFINER;
    `);
    console.log('✓ handle_new_user function created');

    // Create tables (use IF NOT EXISTS for idempotency)
    const tables = [
      `CREATE TABLE IF NOT EXISTS public.profiles (
        id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
        full_name TEXT NOT NULL DEFAULT '',
        phone TEXT DEFAULT '',
        role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'staff', 'user')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )`,
      `CREATE TABLE IF NOT EXISTS public.categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name_ar TEXT NOT NULL,
        name_en TEXT NOT NULL,
        slug TEXT NOT NULL UNIQUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )`,
      `CREATE TABLE IF NOT EXISTS public.products (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE RESTRICT,
        name_ar TEXT NOT NULL,
        name_en TEXT NOT NULL,
        description_ar TEXT DEFAULT '',
        description_en TEXT DEFAULT '',
        price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
        images TEXT[] DEFAULT '{}',
        is_active BOOLEAN NOT NULL DEFAULT true,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )`,
      `CREATE TABLE IF NOT EXISTS public.product_variants (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
        size TEXT NOT NULL,
        stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        UNIQUE(product_id, size)
      )`,
      `CREATE TABLE IF NOT EXISTS public.coupons (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code TEXT NOT NULL,
        type TEXT NOT NULL CHECK (type IN ('percentage', 'fixed')),
        value NUMERIC(10, 2) NOT NULL CHECK (value > 0),
        auto_apply BOOLEAN NOT NULL DEFAULT false,
        conditions JSONB DEFAULT '{}',
        active BOOLEAN NOT NULL DEFAULT true,
        label_ar TEXT DEFAULT '',
        label_en TEXT DEFAULT '',
        max_uses INTEGER,
        used_count INTEGER NOT NULL DEFAULT 0,
        expires_at TIMESTAMPTZ,
        show_countdown BOOLEAN NOT NULL DEFAULT false,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )`,
      `CREATE TABLE IF NOT EXISTS public.orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
        customer_name TEXT NOT NULL,
        customer_phone TEXT NOT NULL,
        customer_address TEXT NOT NULL,
        customer_city TEXT NOT NULL,
        notes TEXT DEFAULT '',
        items JSONB NOT NULL,
        subtotal NUMERIC(10, 2) NOT NULL,
        discount NUMERIC(10, 2) NOT NULL DEFAULT 0,
        shipping NUMERIC(10, 2) NOT NULL DEFAULT 0,
        total NUMERIC(10, 2) NOT NULL,
        coupon_code TEXT,
        payment_method TEXT NOT NULL DEFAULT 'cod',
        status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'shipped', 'delivered')),
        admin_modified BOOLEAN NOT NULL DEFAULT false,
        admin_modified_at TIMESTAMPTZ,
        status_history JSONB DEFAULT '[]',
        notes_admin TEXT DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )`,
    ];

    for (const sql of tables) {
      await client.query(sql);
      console.log('✓ Table created');
    }

    // Enable RLS on all tables
    const rlsTables = ['profiles', 'categories', 'products', 'product_variants', 'coupons', 'orders'];
    for (const tbl of rlsTables) {
      await client.query(`ALTER TABLE public.${tbl} ENABLE ROW LEVEL SECURITY;`);
    }
    console.log('✓ RLS enabled on all tables');

    // Create trigger
    await client.query(`
      DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
      CREATE TRIGGER on_auth_user_created
        AFTER INSERT ON auth.users
        FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
    `);
    console.log('✓ Trigger created');

    // RLS Policies
    const policies = [
      // Profiles
      `DROP POLICY IF EXISTS "profiles_select" ON public.profiles;
       CREATE POLICY "profiles_select" ON public.profiles FOR SELECT USING (true)`,
      `DROP POLICY IF EXISTS "profiles_update" ON public.profiles;
       CREATE POLICY "profiles_update" ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id)`,
      `DROP POLICY IF EXISTS "profiles_update_admin" ON public.profiles;
       CREATE POLICY "profiles_update_admin" ON public.profiles FOR UPDATE TO authenticated
        USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin')
        WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin')`,
      `DROP POLICY IF EXISTS "profiles_delete" ON public.profiles;
       CREATE POLICY "profiles_delete" ON public.profiles FOR DELETE TO authenticated
        USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin')`,
      // Categories
      `DROP POLICY IF EXISTS "categories_select" ON public.categories;
       CREATE POLICY "categories_select" ON public.categories FOR SELECT USING (true)`,
      `DROP POLICY IF EXISTS "categories_insert" ON public.categories;
       CREATE POLICY "categories_insert" ON public.categories FOR INSERT TO authenticated
        WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))`,
      `DROP POLICY IF EXISTS "categories_update" ON public.categories;
       CREATE POLICY "categories_update" ON public.categories FOR UPDATE TO authenticated
        USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))
        WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))`,
      `DROP POLICY IF EXISTS "categories_delete" ON public.categories;
       CREATE POLICY "categories_delete" ON public.categories FOR DELETE TO authenticated
        USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))`,
      // Products
      `DROP POLICY IF EXISTS "products_select" ON public.products;
       CREATE POLICY "products_select" ON public.products FOR SELECT USING (true)`,
      `DROP POLICY IF EXISTS "products_insert" ON public.products;
       CREATE POLICY "products_insert" ON public.products FOR INSERT TO authenticated
        WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))`,
      `DROP POLICY IF EXISTS "products_update" ON public.products;
       CREATE POLICY "products_update" ON public.products FOR UPDATE TO authenticated
        USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))
        WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))`,
      `DROP POLICY IF EXISTS "products_delete" ON public.products;
       CREATE POLICY "products_delete" ON public.products FOR DELETE TO authenticated
        USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))`,
      // Variants
      `DROP POLICY IF EXISTS "variants_select" ON public.product_variants;
       CREATE POLICY "variants_select" ON public.product_variants FOR SELECT USING (true)`,
      `DROP POLICY IF EXISTS "variants_insert" ON public.product_variants;
       CREATE POLICY "variants_insert" ON public.product_variants FOR INSERT TO authenticated
        WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))`,
      `DROP POLICY IF EXISTS "variants_update" ON public.product_variants;
       CREATE POLICY "variants_update" ON public.product_variants FOR UPDATE TO authenticated
        USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))
        WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))`,
      `DROP POLICY IF EXISTS "variants_update_stock" ON public.product_variants;
       CREATE POLICY "variants_update_stock" ON public.product_variants FOR UPDATE TO authenticated
        USING (true) WITH CHECK (stock >= 0)`,
      `DROP POLICY IF EXISTS "variants_update_stock_anon" ON public.product_variants;
       CREATE POLICY "variants_update_stock_anon" ON public.product_variants FOR UPDATE TO anon
        USING (true) WITH CHECK (stock >= 0)`,
      `DROP POLICY IF EXISTS "variants_delete" ON public.product_variants;
       CREATE POLICY "variants_delete" ON public.product_variants FOR DELETE TO authenticated
        USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))`,
      // Coupons
      `DROP POLICY IF EXISTS "coupons_select" ON public.coupons;
       CREATE POLICY "coupons_select" ON public.coupons FOR SELECT USING (true)`,
      `DROP POLICY IF EXISTS "coupons_insert" ON public.coupons;
       CREATE POLICY "coupons_insert" ON public.coupons FOR INSERT TO authenticated
        WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))`,
      `DROP POLICY IF EXISTS "coupons_update" ON public.coupons;
       CREATE POLICY "coupons_update" ON public.coupons FOR UPDATE TO authenticated
        USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))
        WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))`,
      `DROP POLICY IF EXISTS "coupons_delete" ON public.coupons;
       CREATE POLICY "coupons_delete" ON public.coupons FOR DELETE TO authenticated
        USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))`,
      // Orders
      `DROP POLICY IF EXISTS "orders_select" ON public.orders;
       CREATE POLICY "orders_select" ON public.orders FOR SELECT TO authenticated
        USING (user_id = auth.uid() OR (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))`,
      `DROP POLICY IF EXISTS "orders_insert_auth" ON public.orders;
       CREATE POLICY "orders_insert_auth" ON public.orders FOR INSERT TO authenticated
        WITH CHECK (user_id = auth.uid())`,
      `DROP POLICY IF EXISTS "orders_insert_anon" ON public.orders;
       CREATE POLICY "orders_insert_anon" ON public.orders FOR INSERT TO anon
        WITH CHECK (true)`,
      `DROP POLICY IF EXISTS "orders_update" ON public.orders;
       CREATE POLICY "orders_update" ON public.orders FOR UPDATE TO authenticated
        USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))
        WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'staff'))`,
    ];

    for (const sql of policies) {
      try { await client.query(sql); } catch (e) { console.log('  Policy error:', e.message.substring(0, 80)); }
    }
    console.log('✓ RLS Policies created');

    // Grant permissions
    await client.query(`GRANT USAGE ON SCHEMA public TO anon, authenticated;`);
    await client.query(`GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon, authenticated;`);
    await client.query(`GRANT INSERT ON public.orders TO anon;`);
    await client.query(`GRANT INSERT ON public.orders TO authenticated;`);
    await client.query(`GRANT UPDATE (stock) ON public.product_variants TO anon, authenticated;`);
    await client.query(`GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;`);
    console.log('✓ Permissions granted');

    // Create checkout function (SECURITY DEFINER bypasses RLS for guest orders)
    await client.query(`
      CREATE OR REPLACE FUNCTION public.create_checkout_order(
        p_items jsonb,
        p_shipping_name text,
        p_shipping_phone text,
        p_shipping_city text,
        p_shipping_address text,
        p_notes text DEFAULT '',
        p_coupon_code text DEFAULT NULL,
        p_discount numeric DEFAULT 0
      )
      RETURNS json
      LANGUAGE plpgsql
      SECURITY DEFINER
      SET search_path = ''
      AS $func$
      DECLARE
        v_user_id uuid;
        v_subtotal numeric(10,2) := 0;
        v_discount numeric(10,2) := 0;
        v_shipping numeric(10,2);
        v_total numeric(10,2);
        v_order_id bigint;
        v_item jsonb;
        v_product record;
        v_variant record;
        v_full_items jsonb := '[]'::jsonb;
        v_enriched jsonb;
      BEGIN
        v_user_id := auth.uid();
        v_discount := COALESCE(p_discount, 0);

        FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
        LOOP
          SELECT p.id, p.price, p.name_ar, p.name_en, p.images,
                 COALESCE(c.name_ar, '') AS cat_ar, COALESCE(c.name_en, '') AS cat_en
          INTO v_product
          FROM public.products p
          LEFT JOIN public.categories c ON c.id = p.category_id
          WHERE p.id = (v_item->>'product_id')::bigint AND p.is_active = true;

          IF NOT FOUND THEN
            RAISE EXCEPTION 'المنتج غير موجود أو غير متاح' USING ERRCODE = 'P0001';
          END IF;

          SELECT id, stock INTO v_variant
          FROM public.product_variants
          WHERE product_id = v_product.id AND size = v_item->>'size';

          IF NOT FOUND THEN
            RAISE EXCEPTION 'المقاس غير متاح للمنتج' USING ERRCODE = 'P0001';
          END IF;

          IF v_variant.stock < (v_item->>'quantity')::int THEN
            RAISE EXCEPTION 'الكمية المطلوبة غير متوفرة في المخزون' USING ERRCODE = 'P0001';
          END IF;

          v_subtotal := v_subtotal + v_product.price * (v_item->>'quantity')::int;

          v_enriched := jsonb_build_object(
            'productId', v_product.id,
            'size', v_item->>'size',
            'quantity', (v_item->>'quantity')::int,
            'price', v_product.price,
            'name_ar', v_product.name_ar,
            'name_en', v_product.name_en,
            'category', v_product.cat_ar,
            'image', COALESCE(v_product.images[1], '')
          );
          v_full_items := v_full_items || v_enriched;
        END LOOP;
        v_shipping := CASE WHEN (v_subtotal - v_discount) >= 1000 THEN 0 ELSE 50 END;

        v_total := v_subtotal - v_discount + v_shipping;

        INSERT INTO public.orders (
          user_id, customer_name, customer_phone, customer_address, customer_city,
          notes, items, subtotal, discount, shipping, total, coupon_code, payment_method, status
        ) VALUES (
          v_user_id, p_shipping_name, p_shipping_phone, p_shipping_address, p_shipping_city,
          p_notes, v_full_items, v_subtotal, v_discount, v_shipping, v_total,
          p_coupon_code, 'cod', 'pending'
        )
        RETURNING public.orders.id INTO v_order_id;

        FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
        LOOP
          UPDATE public.product_variants
          SET stock = GREATEST(public.product_variants.stock - (v_item->>'quantity')::int, 0)
          WHERE public.product_variants.product_id = (v_item->>'product_id')::bigint
            AND public.product_variants.size = v_item->>'size';
        END LOOP;

        RETURN json_build_object('id', v_order_id, 'order_number', v_order_id::text, 'total', v_total);
      END;
      $func$;
    `);
    await client.query(`GRANT EXECUTE ON FUNCTION public.create_checkout_order TO anon;`);
    await client.query(`GRANT EXECUTE ON FUNCTION public.create_checkout_order TO authenticated;`);
    console.log('✓ Checkout function created');

    // Seed categories
    await client.query(`
      INSERT INTO public.categories (name_ar, name_en, slug) VALUES
        ('ملابس داخلية', 'Innerwear', 'innerwear'),
        ('بيجامات', 'Pajamas', 'pajamas'),
        ('تيشيرتات', 'T-Shirts', 'tshirts'),
        ('بناطيل', 'Pants', 'pants'),
        ('جواكت', 'Jackets', 'jackets'),
        ('فساتين', 'Dresses', 'dresses'),
        ('أطقم', 'Sets', 'sets'),
        ('إكسسوارات', 'Accessories', 'accessories')
      ON CONFLICT (slug) DO NOTHING;
    `);
    console.log('✓ Categories seeded');

    // Seed coupons
    await client.query(`
      INSERT INTO public.coupons (code, type, value, auto_apply, conditions, active, label_ar, label_en) VALUES
        ('AUTO_ITEMS_5', 'percentage', 5, true, '{"minItems": 4}', true,
         'خصم 5% عند شراء 4 قطع أو أكثر', '5% off when buying 4+ items'),
        ('AUTO_AMOUNT_100', 'fixed', 100, true, '{"minAmount": 1000}', true,
         'خصم 100 جنيه للطلبات فوق 1000 جنيه', '100 EGP off for orders over 1000 EGP'),
        ('AUTO_SIZE_4', 'percentage', 10, true, '{"size": "4"}', true,
         'خصم 10% على مقاس 4', '10% off on size 4'),
        ('CUTE10', 'percentage', 10, false, '{}', true,
         'كود CUTE10 → خصم 10% على كل المنتجات', 'Code CUTE10 → 10% off all products'),
        ('WELCOME', 'fixed', 50, false, '{"minAmount": 300}', true,
         'كود WELCOME → خصم 50 جنيه للطلبات فوق 300', 'Code WELCOME → 50 EGP off orders over 300'),
        ('INNER20', 'percentage', 20, false, '{"category": "innerwear"}', true,
         'كود INNER20 → خصم 20% على الملابس الداخلية', 'Code INNER20 → 20% off innerwear')
      ON CONFLICT DO NOTHING;
    `);
    console.log('✓ Coupons seeded');

    // Seed products with variants
    const catRes = await client.query(`SELECT id, slug FROM public.categories`);
    const catMap = {};
    catRes.rows.forEach(r => catMap[r.slug] = r.id);

    const seedProducts = [
      { cat: 'innerwear', name_ar: 'طقم ملابس داخلية قطن 3 قطعة', name_en: 'Cotton Innerwear Set 3 Pieces',
        desc_ar: 'طقم ملابس داخلية قطنية ناعمة وآمنة على بشرة الأطفال',
        desc_en: 'Soft cotton innerwear set safe for children\'s skin',
        price: 185, img: 'https://placehold.co/400x500/F3B423/1D355E?text=طقم+داخلي',
        variants: [{s:'2',st:10},{s:'3',st:8},{s:'4',st:12},{s:'5',st:6},{s:'6',st:4}] },
      { cat: 'pajamas', name_ar: 'بيجامة شتوية قطيفة', name_en: 'Winter Fleece Pajama',
        desc_ar: 'بيجامة شتوية من القطيفة الناعمة، توفر الدفء والراحة',
        desc_en: 'Winter fleece pajama, soft and warm for your child\'s comfort',
        price: 320, img: 'https://placehold.co/400x500/1D355E/F3B423?text=بيجامة',
        variants: [{s:'2',st:7},{s:'3',st:5},{s:'4',st:0},{s:'5',st:9},{s:'6',st:3},{s:'7',st:6}] },
      { cat: 'tshirts', name_ar: 'تيشيرت قطني بأكمام قصيرة', name_en: 'Cotton Short Sleeve T-Shirt',
        desc_ar: 'تيشيرت قطني 100% بأكمام قصيرة، ألوان زاهية',
        desc_en: '100% cotton short sleeve t-shirt, vibrant colors',
        price: 150, img: 'https://placehold.co/400x500/F3B423/1D355E?text=تيشيرت',
        variants: [{s:'2',st:15},{s:'3',st:12},{s:'4',st:10},{s:'5',st:8},{s:'6',st:6},{s:'7',st:4},{s:'8',st:2}] },
      { cat: 'pants', name_ar: 'بنطلون جينز أطفال', name_en: 'Kids Jeans Pants',
        desc_ar: 'بنطلون جينز مريح للأطفال، قماش مرن',
        desc_en: 'Comfortable kids jeans, flexible fabric',
        price: 280, img: 'https://placehold.co/400x500/1D355E/F3B423?text=جينز',
        variants: [{s:'3',st:8},{s:'4',st:10},{s:'5',st:7},{s:'6',st:5},{s:'7',st:0},{s:'8',st:4}] },
      { cat: 'jackets', name_ar: 'جاكت مبطن شتوي', name_en: 'Winter Padded Jacket',
        desc_ar: 'جاكت شتوي مبطن عازل للبرودة',
        desc_en: 'Winter padded jacket, cold-resistant',
        price: 450, img: 'https://placehold.co/400x500/F3B423/1D355E?text=جاكت',
        variants: [{s:'2',st:5},{s:'3',st:7},{s:'4',st:6},{s:'5',st:4},{s:'6',st:3}] },
      { cat: 'dresses', name_ar: 'فستان بناتي دانتيل', name_en: 'Girls Lace Dress',
        desc_ar: 'فستان بناتي أنيق بتفاصيل دانتيل ناعمة',
        desc_en: 'Elegant girls dress with soft lace details',
        price: 380, img: 'https://placehold.co/400x500/1D355E/F3B423?text=فستان',
        variants: [{s:'2',st:6},{s:'3',st:8},{s:'4',st:0},{s:'5',st:5},{s:'6',st:7},{s:'7',st:3}] },
      { cat: 'sets', name_ar: 'طقم صيفي (تيشيرت + شورت)', name_en: 'Summer Set (T-Shirt + Shorts)',
        desc_ar: 'طقم صيفي أنيق مكون من تيشيرت وشورت قطن',
        desc_en: 'Elegant summer set with cotton t-shirt and shorts',
        price: 290, img: 'https://placehold.co/400x500/F3B423/1D355E?text=طقم+صيفي',
        variants: [{s:'2',st:10},{s:'3',st:8},{s:'4',st:6},{s:'5',st:0},{s:'6',st:4}] },
      { cat: 'accessories', name_ar: 'طاقية صيفية واقية من الشمس', name_en: 'Summer Sun Protection Hat',
        desc_ar: 'طاقية صيفية عصرية تحمي طفلك من الشمس',
        desc_en: 'Stylish summer hat protecting your child from sun',
        price: 85, img: 'https://placehold.co/400x500/1D355E/F3B423?text=طاقية',
        variants: [{s:'2',st:20},{s:'3',st:15},{s:'4',st:12},{s:'5',st:8}] },
      { cat: 'pajamas', name_ar: 'بيجامة صيفية قطنية', name_en: 'Summer Cotton Pajama',
        desc_ar: 'بيجامة صيفية خفيفة من القطن العضوي',
        desc_en: 'Light summer pajama made of organic cotton',
        price: 260, img: 'https://placehold.co/400x500/F3B423/1D355E?text=بيجامة+صيفية',
        variants: [{s:'2',st:8},{s:'3',st:10},{s:'4',st:7},{s:'5',st:5},{s:'6',st:0}] },
      { cat: 'innerwear', name_ar: 'فانلة داخلية قطن بأكمام طويلة', name_en: 'Cotton Long Sleeve Undershirt',
        desc_ar: 'فانلة داخلية قطن بأكمام طويلة، ناعمة ومناسبة للشتاء',
        desc_en: 'Cotton long sleeve undershirt, soft and suitable for winter',
        price: 110, img: 'https://placehold.co/400x500/1D355E/F3B423?text=فانلة',
        variants: [{s:'2',st:14},{s:'3',st:12},{s:'4',st:10},{s:'5',st:8},{s:'6',st:6},{s:'7',st:4},{s:'8',st:3}] },
      { cat: 'tshirts', name_ar: 'تيشيرت قطني مطبوع عليه رسوم كرتون', name_en: 'Cotton T-Shirt with Cartoon Print',
        desc_ar: 'تيشيرت قطني بأكمام قصيرة مطبوع عليه رسوم كرتونية',
        desc_en: 'Cotton short sleeve t-shirt with cartoon prints',
        price: 170, img: 'https://placehold.co/400x500/F3B423/1D355E?text=مطبوع',
        variants: [{s:'2',st:18},{s:'3',st:14},{s:'4',st:11},{s:'5',st:0},{s:'6',st:0}] },
      { cat: 'dresses', name_ar: 'فستان تول للأميرات', name_en: 'Princess Tulle Dress',
        desc_ar: 'فستان تول أميري مع تفاصيل لامعة',
        desc_en: 'Princess tulle dress with sparkling details',
        price: 520, img: 'https://placehold.co/400x500/F3B423/1D355E?text=تول',
        variants: [{s:'3',st:4},{s:'4',st:0},{s:'5',st:6},{s:'6',st:3},{s:'7',st:2}] },
    ];

    for (const p of seedProducts) {
      await client.query(`
        WITH ins AS (
          INSERT INTO public.products (category_id, name_ar, name_en, description_ar, description_en, price, images)
          VALUES ($1, $2, $3, $4, $5, $6, ARRAY[$7])
          ON CONFLICT DO NOTHING
          RETURNING id
        )
        SELECT id FROM ins
      `, [catMap[p.cat], p.name_ar, p.name_en, p.desc_ar, p.desc_en, p.price, p.img]);

      const prodRes = await client.query(`SELECT id FROM public.products WHERE name_ar = $1`, [p.name_ar]);
      if (prodRes.rows.length > 0) {
        const pid = prodRes.rows[0].id;
        for (const v of p.variants) {
          await client.query(`
            INSERT INTO public.product_variants (product_id, size, stock)
            VALUES ($1, $2, $3)
            ON CONFLICT (product_id, size) DO UPDATE SET stock = $3
          `, [pid, v.s, v.st]);
        }
      }
    }
    console.log('✓ Products seeded');

    console.log('\n✅ Database setup complete!');
  } catch (err) {
    console.error('Failed:', err.message);
  } finally {
    await client.end();
  }
}

setupDatabase();
